---
- name: install git
  apt:  pkg=git state=installed update_cache=true

- name: install ufw firewall
  apt: pkg=ufw state=installed update_cache=true

- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true
  when: ppastable|success
  register: nginxinstalled
  notify:
    - Start Nginx

- name: Allow ssh through firewall
  ufw: proto=tcp port=22 rule=allow

- name: Allow nginx firewall
  ufw: proto=tcp port=80 rule=allow

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny
